apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  namespace: demo1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1