apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    app: elasticsearch-logging
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: elasticsearch-logging
    spec:
      containers:
        - image: gcr.io/google_containers/elasticsearch:v2.4.1-2
          name: elasticsearch-logging
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace