apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: demo1
  labels:
    app: wordpress
  annotations:
    prometheus.io/probe: "true"
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer