apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: demo1
  labels:
    app: wordpress
  annotations:
    prometheus.io/probe: "true"
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None