apiVersion: v1
kind: Service
metadata:
  name: grafana-monitoring
  namespace: kube-system
  labels:
    app: grafana-monitoring
  annotations:
    prometheus.io/probe: "true"
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: influxdb-grafana