apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb-grafana
  namespace: kube-system
  labels:
    app: influxdb-grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb-grafana
    spec:
      containers:
        - image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
          name: influxdb
          ports:
            - containerPort: 8083
              name: influx
            - containerPort: 8086
              name: api
        - image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana
          env:
            - name: INFLUXDB_SERVICE_URL
              value: http://localhost:8086
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /api/v1/proxy/namespaces/kube-system/services/grafana-monitoring/